service: serverless-step-function-example
frameworkVersion: "3"

package:
  individually: true

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: us-east-1
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: '1'
    NODE_OPTIONS: '--enable-source-maps --stack-trace-limit=1000'

functions: ${file(config/lambdas.yml)}

stepFunctions: ${file(config/stepFunctions.yml)}

resources: ${file(config/resources.yml)}

plugins:
  - serverless-plugin-typescript
  - serverless-prune-plugin
  - serverless-step-functions
  # - serverless-esbuild

# custom:
#   esbuild: ${file(./esbuild.config.js)}