sendSQSMessageLambda:
  handler: src/handlers/sendSQSQueueMessageLambda/sendSQSQueueMessageLambda.handler
  environment:
    ORDER_QUEUE_URL: !GetAtt sendOrderMessageSQSQueue.QueueUrl
  package:
    patterns:
      - '!node_modules/**'
  role:
    Fn::GetAtt:
      - sendSQSMessageLambdaRole
      - Arn
  events:
    - http:
        path: /purchaseOrder
        method: POST


startStateMachineLambda:
  handler: src/handlers/startStateMachineLambda/startStateMachineLambda.handler
  role: 
    Fn::GetAtt:
      - startStateMachineLambdaRole
      - Arn
  package:
    patterns:
      - '!node_modules/**'
  environment:
    STATE_MACHINE_ARN: arn:aws:states:us-east-1:625099618520:stateMachine:purchaseOrder
  events:
    - sqs:
        arn: !GetAtt sendOrderMessageSQSQueue.Arn


validateSQSMessageLambda:
  handler: src/handlers/validateSQSMessageLambda/validateSQSMessageLambda.handler
  package:
    patterns:
      - '!node_modules/aws-sdk/**'
      - '!node_modules/@aws-sdk/**'
      - '!node_modules/serverless/**'
  role:
    Fn::GetAtt:
      - validateSQSMessageLambdaRole
      - Arn


saveOrderDetailsLambda:
  handler: src/handlers/saveOrderDetailsLambda/saveOrderDetailsLambda.handler
  environment:
    ORDER_TABLE_NAME: !Ref Orders
  package:
    patterns:
      - '!node_modules/**'
  role:
    Fn::GetAtt:
      - saveOrderDetailsLambdaRole
      - Arn


processOrderDetailsLambda:
  handler: src/handlers/processOrderDetailsLambda/processOrderDetailsLambda.handler
  environment:
    STOCKS_TABLE_NAME: !Ref Stocks
  package:
    patterns:
      - '!node_modules/**'
  role:
    Fn::GetAtt:
      - processOrderDetailsLambdaRole
      - Arn


handleProcessOrderLambda:
  handler: src/handlers/handleProcessOrderLambda/handleProcessOrderLambda.handler
  environment:
    ORDER_TABLE_NAME: !Ref Orders
  package:
    patterns:
      - '!node_modules/**'
  role:
    Fn::GetAtt:
      - handleProcessOrderLambdaRole
      - Arn


handleResponseLambda:
  handler: src/handlers/handleResponseLambda/handleResponseLambda.handler
  environment:
    SNS_TOPIC_ARN: !Ref OrderEmailSNSTopic
    DLQ_QUEUE_URL: !GetAtt deadLetterQueue.QueueUrl
  package:
    patterns:
      - '!node_modules/**'
  role:
    Fn::GetAtt:
      - handleResponseLambdaRole
      - Arn
