Comment: "Step function to process the order details"
StartAt: saveOrderDetails
States:
  saveOrderDetails:
    Type: Task
    Resource: arn:aws:lambda:us-east-1:625099618520:function:serverless-step-function-example-dev-saveOrderDetailsLambda
    InputPath: $
    OutputPath: $
    Next: processOrders

  processOrders:
    Type: Map
    InputPath: "$.orderArray"
    ResultPath: "$.result"
    OutputPath: $
    MaxConcurrency: 1
    Iterator:
      StartAt: processOrderDetails
      States:
        processOrderDetails:
          Type: Task
          Resource: arn:aws:lambda:us-east-1:625099618520:function:serverless-step-function-example-dev-processOrderDetailsLambda
          InputPath: $
          OutputPath: "$"
          End: true
    Next: handleProcessOrder
  
  handleProcessOrder:
    Type: Task
    Resource: arn:aws:lambda:us-east-1:625099618520:function:serverless-step-function-example-dev-handleProcessOrderLambda
    InputPath: $
    OutputPath: $
    End: true
