Resources:
  handleResponseLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: handleResponseLambdaRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: handleResponseLambdaRolePolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - sns:Publish
                  - sqs:SendMessage
                Resource:
                  - !Ref OrderEmailSNSTopic
                  - !GetAtt deadLetterQueue.Arn